#Configure this

sql:
  driver: MySQL
  database-name: kingdoms
  table-prefix:
  user: sqluser
  password:
  host: localhost
  port: 3306

use-economy: true
village-cost: 1000
upkeep-cost: 100
upkeep-interval: 12h
default-village-balance: 100
claim-cost: 100

teleport-delay: 5

towns-reflect-damage: false