#Configure this

sql:
  driver: MySQL
  database-name: parent
  table-prefix: parent
  user: sqluser
  password: somepass
  host: 127.0.0.1
  port: 3306

use-economy: true
village-cost: 1000
upkeep-cost: 100
upkeep-interval: 12h
default-balance: 100
claim-cost: 100

towns-reflect-damage: false